### ISSUE TITLE
Можно ли передать в такой vue какие-то данные на вход от php ? 

### ISSUE THREAD

**Issue by amikha1lov** [denx-b/bitrix-vue-component#2]
Например, хотелось бы сделать карточки в каталоге на вью, но нужно передать id товара в сам vue

**Comment by denx-b** [comment]
Как вариант – разместить кусок скрипта, который регистрирует глобальную переменную только с нужным вам идентификатором товара
`<script>
let globalProductId = <?=$arResult['ID']?>
</script>`

Тогда во vue у вас будет доступ к переменной globalProductId и вы сможете сделать ajax-запрос на сервер для запроса данных по товару.
